### ISSUE TITLE
我已经改了参数和数据集，loss 也正常，但是测试测试不出东西

### ISSUE THREAD

**Issue by lzzzzzzzzz** [balancap/SSD-Tensorflow#289]
具体的参数等看我上一个问题
参数的修改，数据集的修改，都改了
收敛也正常，不知道那边出错了

there is more detail in my last question.
i have chaged all the things,and train loss  is normal.
But i can't see angthing show  on  my pics when I test  on my own trainmodel.

**Comment by lzzzzzzzzz** [comment]
[https://github.com/balancap/SSD-Tensorflow/issues/265](url)

**Comment by woshilicong33** [comment]
解决了吗？

**Comment by ZhuDaQing** [comment]
我也是，你决绝了吗？

**Comment by oftenliu** [comment]
请问，有人解决了吗？我训练两个类别的也遇到了这个问题

**Comment by creabob** [comment]
I met the same problems and I modify notebooks/ssd_tests.ipynb-- process_image( ) method. in this mehod parameter select_threshold 's default value is 0.5 and i change to 0.3 or smaller.run again it can get some bboxes. but i think it have not figured out because most bbox's confidence score between 2 to 3 and fill with lots of wrong bboxes. i think the reason maybe the objects so small in the 1080*720 picture. object may around 30*30. besides i got a big loss betwend 8 to 15 and it cannot converge. 
so if u get same situation please give some solution.
